### ISSUE TITLE
Unimplemented data type FLOAT16 (1) in tensor

### ISSUE THREAD

**Issue by b0ssplz** [shaunak99/hand_gesture_recognition#1]
When i try to run this code the following error occurs:
```
ValueError: Unimplemented data type FLOAT16 (1) in tensor
Unimplemented data type FLOAT16 (1) in tensor
```
There's ton of `Unimplemented data type FLOAT16 (1) in tensor` errors.

It seems like something wrong is with `joint_model` because `palm_model` before loaded correctly. It gets stuck on this line:
`        self.interp_joint = tf.lite.Interpreter(joint_model)`

**Comment by shaunak99** [comment]
Hi, my due apologies for the late reply.

What version of tensorflow are you using? 
Try upgrading to tensorflow 2.2

This particular error was mostly thrown as earlier versions of TensorFlow Lite do not support float16 quantization

Please do let me know if that helps solve the issue!
More details on float16 quantization can be found [here](https://www.tensorflow.org/lite/performance/post_training_float16_quant)
