### ISSUE TITLE
?questions how do I implement other gestures ??

### ISSUE THREAD

**Issue by adarshx11** [shaunak99/hand_gesture_recognition#2]
how do i implement human sign gestures for human Sign Language

**Comment by shaunak99** [comment]
This repo is a very basic implementation which uses classical image techniques and isn't very robust.
However, for your sign language, you may try exploring some hand sign datasets or create your own, and train a network to recognize the hand sign. Having trained that network, you may then integrate the live stream handpose from this repo with the hand sign recognition network that you created. 
This is just a suggestion but I encourage you to explore other existing methods for hand sign language that already exist.
